import AuthProvider from "@/context/Auth";
import type { Metadata } from "next";
import { getServerSession } from "next-auth/next";
import { lato } from "@/utils/AppFont";
import classNames from "classnames";
import Screen from "@/components/common/Screen";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={classNames("min-h-screen", lato.className)}>
        <AuthProvider session={session!}>{children}</AuthProvider>
      </body>
    </html>
  );
}
