import AuthProvider from "@/context/Auth";
import type { Metadata } from "next";
import { getServerSession } from "next-auth/next";
import { lato } from "@/utils/AppFont";
import "./globals.css";
import Screen from "@/components/common/Screen";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={lato.className}>
        <AuthProvider session={session!}>
          <Screen>{children}</Screen>
        </AuthProvider>
      </body>
    </html>
  );
}
